branch-defaults:
  master:
    environment: drchrono
    group_suffix: null
global:
  application_name: drchrono-example
  branch: null
  default_ec2_keyname: drchrono_key
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
